# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@0
    displayName: 'Terraform Install'
    inputs:
      terraformVersion: 'latest'

  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      allowTelemetryCollection: true
      backendServiceArm: 'Aseem-Azure Sub'
      backendAzureRmResourceGroupName: 'Aseem-Terraform-Training'
      backendAzureRmStorageAccountName: 'aseemterraformuks'
      backendAzureRmContainerName: 'aseemterratrain'
      backendAzureRmKey: 'terraform.tfstate'
      backendAzureRmResourceGroupLocation: 'uksouth'
      backendType: 'azurerm'
      ensureBackend: true 

  - task: TerraformCLI@0
    displayName: 'Terraform Validate'
    inputs:
      command: 'validate'
      allowTelemetryCollection: true

  - task: TerraformCLI@0
    displayName: 'Terraform Plan'
    inputs:
      command: 'plan'
      environmentServiceName: 'Aseem-Azure Sub'
      allowTelemetryCollection: true

  - task: TerraformCLI@0
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      environmentServiceName: 'Aseem-Azure Sub'
      allowTelemetryCollection: true