# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: belal_backend_variable_group

jobs:
- template: jobs/terraform_validate.yml

- template: jobs/terraform_plan.yml

- template: jobs/terraform_apply.yml