steps:
  - task: TerraformCLI@0
    displayName: 'Terraform Apply'
    inputs:
      command: 'apply'
      environmentServiceName: $(backendServiceArm)
      allowTelemetryCollection: true
      commandOptions: '$(Pipeline.Workspace)/terraform_plan/plan-results.tfplan'