jobs:
  - job: Terraform_Plan
    displayName: 'Terraform Plan'
    dependsOn: Terraform_Validate
    steps:
      - template: ../tasks/terraform-install.yml

      - template: ../tasks/terraform-init.yml

      - template: ../tasks/mkdir.yml

      - template: ../tasks/terraform-plan.yml

      - template: ../tasks/artifact-publish.yml

      - template: ../tasks/set-variable.yml