jobs:
- deployment: Terraform_Apply
  continueOnError: true
  environment: $(Environment)
  strategy:
    runOnce:
      deploy:
        steps:

        - template: ../tasks/terraform-install.yml

        - template: ../tasks/terraform-init.yml
        
        - template: ../tasks/artifact-download.yml
        
        - template: ../tasks/terraform-apply.yml