jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    dependsOn: Terraform_Plan
    steps:
      - template: ../tasks/terraform-install.yml

      - template: ../tasks/terraform-init.yml

      - template: ../tasks/terraform-apply.yml