jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    steps:
      - template: ../tasks/terraform-install.yml

      - template: ../tasks/terraform-init.yml
      
      - template: ../tasks/artifact-download.yml
      - template: ../tasks/bash.yml
      #- template: ../tasks/terraform-apply.yml